extends: eye
rules:
  react/jsx-curly-newline:
    - error
    - multiline: consistent
      singleline: consistent
  spaced-comment:
    - error
    - always
    - block:
        exceptions: [ \ ]
  prefer-template:
    - off
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-fallthrough:
    - off
  no-async-promise-executor:
    - off
  no-unreachable:
    - off
  no-compare-neg-zero:
    - off
  key-spacing:
    - off